### ISSUE TITLE
Code Review for Indraneel

### ISSUE THREAD

**Issue by hughjazzman** [AY2223S1-CS2113-T18-1b/tp#109]
# @indraneelrp

- [ ] Consider [adding JavaDoc to all `public` methods](https://se-education.org/guides/conventions/java/index.html#comments).

https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/Parser.java#L38

- [ ] Perhaps this name could be more informative?

https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/Parser.java#L48

- [ ] Consider [adding a `// Fallthrough` statement here](https://se-education.org/guides/conventions/java/index.html#layout).
> The explicit `//Fallthrough` comment should be included whenever there is a `case` statement without a `break` statement.

https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/Parser.java#L88

- [ ] Perhaps [constants should be in all uppercase](https://se-education.org/guides/conventions/java/index.html#naming).

https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/Duke.java#L10-L11

**Comment by redders7** [comment]
@indraneelrp Issue seems to be fixed, perhaps it should be closed?
