### ISSUE TITLE
Code Review for Matthew

### ISSUE THREAD

**Issue by hughjazzman** [AY2223S1-CS2113-T18-1b/tp#110]
# @matthewphua

- [x] Consider [adding JavaDoc to all `public` methods](https://se-education.org/guides/conventions/java/index.html#comments). This includes the `execute()` methods.

https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/Parser.java#L203
https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/Parser.java#L211

- [x] This may be a typo.

https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/FindCommand.java#L7
```Java
    private final String listDelimiter = ". ";
```

- [x] Consider refactoring `ListCommand` and `FindCommand` `execute()` methods, as there could be [code duplication](https://nus-cs2113-ay2223s1.github.io/website/se-book-adapted/chapters/codeQuality.html#minimise-code-duplication).

- [x] Consider restructuring this code to [avoid nesting](https://nus-cs2113-ay2223s1.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-deep-nesting).

https://github.com/AY2223S1-CS2113-T18-1b/tp/blob/224c0086d71e7a7336643e91dfc1ce60fbec6a3a/src/main/java/seedu/duke/RemoveCommand.java#L21-L29

**Comment by matthewphua** [comment]
@hughjazzman How would you recommend to fix code duplication? Obviously I would create a helper function that both classes would be able to access. Would it be ok if I add it to the Command class (despite it being abstract)?

**Comment by hughjazzman** [comment]
Yes, `abstract` classes can have non-abstract methods. Declaring a `class` as `abstract` simply means no object of the `class` can be instantiated.

**Comment by matthewphua** [comment]
I'm not sure If I can do that actually because they have different behaviors. One of them checks for a search term and then the other one just adds it within the if conditions...
