### ISSUE TITLE
[PE-D][Tester C] Does not check for missing parameters

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T18-1b/tp#83]
Command does not check for missing parameters e.g. `/movie`, `/genre` i.e. all the below commands result in the app crashing

- `add /movie`
- `add /movie test /review`
- `add /movie test /review 99 /date`

High priority as in any possible scenario your app should not crash

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: winston-lim/ped#1

**Comment by matthewphua** [comment]
I've fixed
