### ISSUE TITLE
[PE-D][Tester A] Broken link in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T18-1b/tp#91]
The User guide has a broken link as shown below in the screenshot

![image.png](https://raw.githubusercontent.com/shengiv/ped/main/files/01eff56f-eee5-4e6b-82cb-8eef3250c819.png)

![image.png](https://raw.githubusercontent.com/shengiv/ped/main/files/d61c6e70-0daa-42a6-88b7-3b92a4d8c7b7.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: shengiv/ped#2

**Comment by naz019** [comment]
Link has been fixed
