### ISSUE TITLE
[PE-D][Tester C] Storage fails due to unhandled exceptions

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T18-1b/tp#95]
Due to runtime errors, when the app crashes, none of the data is stored. This may be due to you not saving the file after each command, but after the `bye` command.

You can either
1. Have a generic ExceptionManager class that handles all exceptions so that your app never crashes and always gracefully exits
AND/OR
2. Persist data after each command, instead of after a user exists the application

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: winston-lim/ped#5

**Comment by indraneelrp** [comment]
Fixed
