### ISSUE TITLE
[PE-D][Tester B] Program crashes on add command when "/" is used as movie title.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T18-1b/tp#99]
On using add command, if "/" character is used in the title, the program crashes.

Payload: add /movie inception/inception2 /rating a /date 10-01-2020 /genre thriller

![image.png](https://raw.githubusercontent.com/wcwy/ped/main/files/b7cf4ce9-488d-460f-9d24-ed7dfc5d6d05.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: wcwy/ped#7

**Comment by matthewphua** [comment]
I think I fixed?? But can someone verify.

**Comment by redders7** [comment]
Fixed by #118
